### ISSUE TITLE
Feature Request: Granularity of fired events 

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#11]
As we discussed in the other issue, there's need for granularity option for events. I guess there's use case for setting this in every event. For instance, I would love to have instant response when I resize circle. It's what we're used to - reactivity that comes with vue. In circle, this could be implemented as step-size="1000" (in meters), which would also change step of drag/circle expansion.

**Comment by xon52** [comment]
I agree. The issue is granularity should change with zoom. If you say 1000m, you cannot move it on zoom 22, but on zoom 0 it will be every pixel. As I said, I made a formula, but that was me testing, writing down step-size against zoom level, and then finding a formula that was close to those points. Do you have any ideas for how to overcome this?

**Comment by voquanghoa** [comment]
I have the same issue now with the circles and markers. 
I think it's simple to change 

```js
return Math.abs(newPosition.lat - oldPosition.lat) > 0.001 || Math.abs(newPosition.lng - oldPosition.lng) > 0.001
```

So that the number `0.001` can be changed by an option from somewhere.

I hope this change will be available soon.

Thanks.

**Comment by xon52** [comment]
Custom sensitivity was added to Marker and will be added to Circle and Rectangle soon in this issue: #41
