### ISSUE TITLE
Fix cluster thrashing while dragging map

### ISSUE THREAD

**Issue by treystout** [xon52/x5-gmaps#84]
I think this [event binding](https://github.com/xon52/x5-gmaps/blob/master/src/components/Cluster.vue#L142) should only refresh on `idle` not `bounds_changed`. Bounds changed gets call a *lot* while dragging

**Comment by xon52** [comment]
This is a challenging one. There are a lot of `bounds_changed` events in Google Maps and there are a lot of cases you do not want to wait for it to be `idle` before you do something.

So pretty much every component has a `bounds_changed` event:
`<gmaps-map />` just emit's every `bounds_changed` and `center_changed` event maps fires.
`<gmaps-marker />` has some logic to test that the last position is a significant change before it fires (and this sensitivity is controlled via the `sensitivity` prop):

```js
// This is a lot of code to be run every time Google Maps fires that event
  public changedPosition(): false | google.maps.LatLngLiteral {
    const oldPosition = this._options.position as google.maps.LatLngLiteral;
    // This function is fired when a marker is replaced by Vue (and options is undefined)
    if (!oldPosition) return false;
    const newPosition = this.marker!.getPosition()!.toJSON();
    return Math.abs(newPosition.lat - oldPosition.lat) > this.sensitivity ||
      Math.abs(newPosition.lng - oldPosition.lng) > this.sensitivity
      ? newPosition
      : false;
  }
```

Now my conundrum is, until a reasonable sized function is attached to the event, it is far more performant to just let the emit happen, rather than trying to filter through when it should/shouldn't be fired. Google Maps is actually firing them anyway (and that's unstoppable), the question is whether Vue is passing them on or not.

For the cluster component, it's another performance question because it's effectively virtualised - it doesn't load every item onto the map and let you pan, it actually checks on every move where you are and has a buffer zone around that window to populate. If I used the `idle` event like you suggest, the map would be potentially blank until you stopped long enough for the map to be "idle".

After all that background, I'm keen to hear examples of how these events are hurting you (I know they're excessive, but it was the best balance I could find in my tests). And of course suggestions I may not have thought of.

**Comment by treystout** [comment]
I appreciate the explanation. I'm currently only drawing test sets for customers but my results are typically 50-100 random GPS coords all over north america. See video below to see individual pins flashing (they are just some free SVG I found on the web)

https://user-images.githubusercontent.com/751002/129274315-f9bed82b-3684-4007-af1f-615e75ce0508.mp4

I also zoomed out to show a mix of clusters and pins (there is a single gmaps-cluster component on the page, no individual gmaps-markers)

What would stop the flashing in your opinion if not the event handler we were discussing?

**Comment by xon52** [comment]
I see. And can reproduce even using standard markers. The problem is in the `refresh()` function itself whereby it is clearing and re-entering data. I might need to do something more fancy there to add and remove rather than clear and add. Will take a look at it this weekend if I get a chance.

**Comment by xon52** [comment]
As an update. After messing around for a couple of hours I remember why I did this. Vue has a horrible way of dying if you start deleting and adding things in an array/object used by `v-for`. Had two hours of this:
![image](https://user-images.githubusercontent.com/30713944/129369093-c98f0213-0583-465c-af44-e1f41fe70a75.png)
And my testing environment is broken since switching this project to TS, so been super slow.
I have a few more things to try, but no luck on this yet.

**Comment by xon52** [comment]
Gave up and changed to the idle event, along with a few other improvements. Try it out and let me know.

Thanks for your suggestions @treystout 👍
